//! The model catalogue effort controls are narrowed with: the snapshot built into the binary (`assets/model-catalog.json`,
//! regenerated by `acpira model-catalog --out <file>`), superseded by a daily refresh from models.dev cached at
//! `<root>/catalog/models.json`, which every window shares. A failed refresh keeps whatever is loaded

use std::path::{Path, PathBuf};
use std::sync::{Arc, LazyLock};
use std::time::{Duration, SystemTime};

use anyhow::{Result, anyhow};
use parking_lot::RwLock;

use acpira_shared::model_catalog::{Catalog, CatalogFile, MODELS_DEV_URL, trim_models_dev};

use crate::store::transcript_store::LogFn;
use crate::util::now_iso;

const SNAPSHOT: &str = include_str!("../assets/model-catalog.json");
const MAX_AGE: Duration = Duration::from_secs(24 * 3600);
/// `0` turns the network refresh off (the test suites' sidecars)
pub const REFRESH_ENV: &str = "ACPIRA_CATALOG_REFRESH";

static CURRENT: LazyLock<RwLock<Arc<Catalog>>> =
  LazyLock::new(|| RwLock::new(Arc::new(Catalog::new(serde_json::from_str(SNAPSHOT).unwrap_or_default()))));

pub fn current() -> Arc<Catalog> {
  CURRENT.read().clone()
}

fn install(file: CatalogFile) {
  *CURRENT.write() = Arc::new(Catalog::new(file));
}

pub fn cache_path(root: &Path) -> PathBuf {
  root.join("catalog").join("models.json")
}

/// Download models.dev and trim it; None when the server answers 304 to `etag`
pub async fn fetch(etag: Option<String>) -> Result<Option<CatalogFile>> {
  tokio::task::spawn_blocking(move || {
    let agent: ureq::Agent =
      ureq::Agent::config_builder().timeout_global(Some(Duration::from_secs(60))).http_status_as_error(false).build().into();
    let mut req = agent.get(MODELS_DEV_URL).header("accept", "application/json");
    if let Some(tag) = &etag {
      req = req.header("if-none-match", tag.as_str());
    }
    let mut res = req.call()?;
    match res.status().as_u16() {
      304 => return Ok(None),
      200..300 => {}
      s => return Err(anyhow!("models.dev HTTP {s}")),
    }
    let tag = res.headers().get("etag").and_then(|v| v.to_str().ok()).map(str::to_owned);
    let text = res.body_mut().with_config().limit(64 * 1024 * 1024).read_to_string()?;
    let file = trim_models_dev(&serde_json::from_str(&text)?, &now_iso(), tag);
    if file.models.is_empty() {
      return Err(anyhow!("models.dev listed none of the catalogue vendors"));
    }
    Ok(Some(file))
  })
  .await?
}

async fn write(path: &Path, text: &str) -> Result<()> {
  if let Some(dir) = path.parent() {
    tokio::fs::create_dir_all(dir).await?;
  }
  let tmp = path.with_extension(format!("json.{}.tmp", std::process::id()));
  tokio::fs::write(&tmp, text).await?;
  tokio::fs::rename(&tmp, path).await?;
  Ok(())
}

/// Adopt the cached catalogue when it is newer than the built-in one, then refresh it once it is a day old
pub async fn refresh(root: PathBuf, log: LogFn) {
  let path = cache_path(&root);
  let cached = tokio::fs::read_to_string(&path).await.ok().and_then(|t| serde_json::from_str::<CatalogFile>(&t).ok());
  let cached = cached.filter(|f| !f.models.is_empty());
  if let Some(f) = &cached
    && f.fetched_at > current().file.fetched_at
  {
    install(f.clone());
  }
  if std::env::var(REFRESH_ENV).is_ok_and(|v| v == "0") {
    return;
  }
  let age = std::fs::metadata(&path).and_then(|m| m.modified()).ok().and_then(|t| SystemTime::now().duration_since(t).ok());
  if cached.is_some() && age.is_some_and(|a| a < MAX_AGE) {
    return;
  }
  let text = match fetch(cached.as_ref().and_then(|f| f.etag.clone())).await {
    // Unchanged upstream: rewrite the cache so its age restarts
    Ok(None) => cached.map(|f| f.to_json()),
    Ok(Some(file)) => {
      log(&format!("model catalog: {} models from models.dev", file.models.len()));
      let text = file.to_json();
      install(file);
      Some(text)
    }
    Err(e) => {
      log(&format!("model catalog refresh failed: {e}"));
      None
    }
  };
  if let Some(text) = text
    && let Err(e) = write(&path, &text).await
  {
    log(&format!("model catalog cache write failed: {e}"));
  }
}

#[cfg(test)]
mod tests {
  #[test]
  fn the_built_in_snapshot_parses() {
    let c = super::current();
    assert!(c.file.models.len() > 50);
    assert!(c.get("claude-opus-4-6").is_some());
  }
}
